### ISSUE TITLE
minor doc issues and table_name prefix

### ISSUE THREAD

**Issue by SebG-js** [tensorchord/pgvecto.rs-py#11]
Thank you for this python lib 0.2.1.
I have noticed some issues in the SDK doc : 

- table_name -> collection_name

PGVectoRs(
            db_url=url,
            **collection_name**="docs",
            dimension=1024,
            recreate=False
        )

- add_records -> insert 

An issue with the code :
- if you choose "docs" as collection_name, the table created in db is collection_docs. A **prefix** is added.
It is not explained in the doc : 
"**table_name** (str): **name** of the table."

**Comment by gaocegege** [comment]
cc @cutecutecat

**Comment by cutecutecat** [comment]
Thanks for your feedback, these errors will be fix in next release.
